### ISSUE TITLE
Can't Search Crashes By Tag

### ISSUE THREAD

**Issue by airbreather** [OpenMods/OpenData#29]
The OpenEye site has a "Tag" field for filtering crashes, but when I just search by "Tag", the request times out for me and I can't search crashes again for several minutes.

I'm guessing the underlying DB doesn't have an index to optimize this.  This would be **incredibly** useful for me, as a modpack developer / maintainer, to be able to look at what crashes people are seeing with the modpack.  There's been a report of a crash that only some people can repro, and I don't happen to be one of those people.

Is there another way I should be trying this kind of a search?  Maybe a magical command to send to MissOpenEye on the IRC channel?

**Comment by boq** [comment]
Yup, we were missing index for this. Added.

Though we are still missing one for mod+tag, but this is limitation of our DB.

**Comment by airbreather** [comment]
Awesome, thanks.  Searches work exactly like I was hoping they would now.

Less awesome is the number of crashes that come up for our modpack, but that's my problem.

Closed.
