### ISSUE TITLE
Latest Java getting Old Java Version Warning

### ISSUE THREAD

**Issue by ThomasAunvik** [OpenMods/OpenData#30]
I get this issue where i get Old Java Version when i have the latest version, in ProgramFiles/Java i have these 3 folders: jdk1.8.0_51, jre1.8.0_60 and jre1.8.0_121,

At [Java Download](https://www.java.com/en/download/win10.jsp) it says that the reccomended version is:

> Recommended Version 8 Update 121 (filesize: 721 KB)

These are the images i have:
![Outdated Java](http://i.imgur.com/T1SrhLT.png)
![Update Checker](http://i.imgur.com/8FhMtUZ.png)

**Comment by boq** [comment]
OpenEye should not print this message, if Java version is over 1.8.0_111 (or something like that). It may also be printed, if there are some network problems, but this is less probable.

Please check if Minecraft actually uses recent version - it should be printed in top right corner of debug screen.

Note: it seems that new launcher uses 1.8.0_25 by default, unless explicitly changed.

**Comment by ThomasAunvik** [comment]
I have an update:
Java Folders:
jre1.8.0_121
jdk1.8.0_121

That is the only folders i have right now. But it is still doing that.

I use Curse to handle my modpack as i downloaded the mod there, but it might seem to use its Native Launcher (New Launcher)
Yes, as it seems it is using 1.8.0_25

After changing to the Jar Launcher (Old Launcher) Latest Java Version it seems to work without a warning. So that fixes it.
