### ISSUE TITLE
[1.12.1] Crash on startup

### ISSUE THREAD

**Issue by HendrikJ79** [OpenMods/OpenData#33]
Crash during startup:

OpenEYE log: https://openeye.openmods.info/crashes/a547bd21c515a10c53ce7d6be01da136
Complete Crash-log: https://gist.github.com/HendrikJ79/673b584ac395d889a2780faf9526c132

**Note/Edit:**
Searched entire PC for document: hello.txt but cant find it

**Comment by boq** [comment]
change `crashOnStartup` in `config/OpenEye.json` back to false.
