### ISSUE TITLE
[Suggestion] Give openEye the ability to start profiling

### ISSUE THREAD

**Issue by mcenderdragon** [OpenMods/OpenData#35]
OpenEye is a realy good tool as it give the devs crashes even if the players dont. Lately we had issues on our server: the TPS suddenly drops under 1 for about 10 minuits and before we can get visual VM running it is gone.

I would suggest to add a config option to start profiling as soon as the server starts to print the "Skipped x ticks" line. I am sure this would help alot of people.

**Comment by boq** [comment]
How about using [Sampler](https://minecraft.curseforge.com/projects/sampler)? It can be activated with command.

**Comment by mcenderdragon** [comment]
yeah, the /debug start/stop is similar, the problem is, we are not fast enough to start this while it is happening.
Or is this possebile by using the "event-based" command triggering from sampler ?

**Comment by boq** [comment]
Seems like `/sampler trigger ticktime <ms>` may be exactly that.
